### ISSUE TITLE
Wrong type since JS-Controller 3.3

### ISSUE THREAD

**Issue by metaxa1** [iobroker-community-adapters/ioBroker.synology#44]
Unfortunately, after updating to 1.1.3, I still have error messages regarding the data point specifications:

`
<html>
<body>

synology.0 | 2021-09-27 20:50:34.710 | info | State value to set for "synology.0.DiskStationManager.vol_info.volume_1.used_size" has to be type "number" but received type "string"
-- | -- | -- | --
synology.0 | 2021-09-27 20:50:10.279 | info | State value to set for "synology.0.DiskStationManager.vol_info.volume_1.used" has to be type "number" but received type "string"

</body>
</html>`

I have already deleted the affected data points and had the adapter recreate them. Unfortunately, the mistake remains.

**Comment by foxriver76** [comment]
```
2021-09-28 10:00:23.471 | info | State value to set for "synology.0.FileStation.info.items.3" has to be stringified but received type "object"
-- | -- | --
synology.0 | 2021-09-28 10:00:23.469 | info | State value to set for "synology.0.FileStation.info.items.2" has to be stringified but received type "object"
synology.0 | 2021-09-28 10:00:23.468 | info | State value to set for "synology.0.FileStation.info.items.1" has to be stringified but received type "object"
synology.0 | 2021-09-28 10:00:23.468 | info | State value to set for "synology.0.FileStation.info.items.0" has to be stringified but received type "object"
```

**Comment by th4git** [comment]
Looks similar with latest adapter:

```
synology-Adapter version: 2.0.1
JS-Controller version: 3.3.18
Node version: v14.17.5
Operating system: Raspbian GNU/Linux 10 (buster) on RaspberryPi 4
```

Running adapter after manually deleting the states-tree below synology.0.* results in many wrong type errors at the log:

```
synology.0 2021-12-12 18:52:42.783	info	State value to set for "synology.0.SurveillanceStation.HomeMode.geo_radius" has to be type "string" but received type "number"
synology.0 2021-12-12 18:52:42.782	info	State value to set for "synology.0.SurveillanceStation.HomeMode.geo_lng" has to be type "string" but received type "number"
synology.0 2021-12-12 18:52:42.781	info	State value to set for "synology.0.SurveillanceStation.HomeMode.geo_lat" has to be type "string" but received type "number"
synology.0 2021-12-12 18:52:42.781	info	State value to set for "synology.0.SurveillanceStation.HomeMode.onetime_enable_on" has to be type "string" but received type "boolean"
synology.0 2021-12-12 18:52:42.780	info	State value to set for "synology.0.SurveillanceStation.HomeMode.onetime_disable_on" has to be type "string" but received type "boolean"
synology.0 2021-12-12 18:52:42.779	info	State value to set for "synology.0.SurveillanceStation.HomeMode.notify_on" has to be type "string" but received type "boolean"
synology.0 2021-12-12 18:52:42.761	info	State value to set for "synology.0.SurveillanceStation.cameras.Camera2.port" has to be type "string" but received type "number"
synology.0 2021-12-12 18:52:42.760	info	State value to set for "synology.0.SurveillanceStation.cameras.Camera2.id" has to be type "string" but received type "number"
synology.0 2021-12-12 18:52:42.741	info	State value to set for "synology.0.SurveillanceStation.cameras.Camera1.port" has to be type "string" but received type "number"
synology.0 2021-12-12 18:52:42.740	info	State value to set for "synology.0.SurveillanceStation.cameras.Camera1.id" has to be type "string" but received type "number"
synology.0 2021-12-12 18:52:42.709	info	State value to set for "synology.0.SurveillanceStation.info.remindQuickconnectTunnel" has to be type "string" but received type "boolean"
synology.0 2021-12-12 18:52:42.708	info	State value to set for "synology.0.SurveillanceStation.info.enableVideoRelay" has to be type "string" but received type "boolean"
synology.0 2021-12-12 18:52:42.707	info	State value to set for "synology.0.SurveillanceStation.info.maxCameraSupport" has to be type "string" but received type "number"
synology.0 2021-12-12 18:52:42.706	info	State value to set for "synology.0.SurveillanceStation.info.liscenseNumber" has to be type "string" but received type "number"
synology.0 2021-12-12 18:52:42.705	info	State value to set for "synology.0.SurveillanceStation.info.isLicenseEnough" has to be type "string" but received type "number"
synology.0 2021-12-12 18:52:42.704	info	State value to set for "synology.0.SurveillanceStation.info.cameraNumber" has to be type "string" but received type "number"
synology.0 2021-12-12 18:52:42.703	info	State value to set for "synology.0.DownloadStation.info.version" has to be type "string" but received type "number"
synology.0 2021-12-12 18:52:42.697	info	State value to set for "synology.0.FileStation.info.items.1" has to be stringified but received type "object"
synology.0 2021-12-12 18:52:42.695	info	State value to set for "synology.0.FileStation.info.items.0" has to be stringified but received type "object"
synology.0 2021-12-12 18:52:42.683	info	State value to set for "synology.0.DiskStationManager.info.serviceVolSize" has to be type "string" but received type "number"
synology.0 2021-12-12 18:52:42.676	info	State value to set for "synology.0.DiskStationManager.info.version" has to be type "string" but received type "number"
synology.0 2021-12-12 18:52:39.971	info	DSM 2

```

Would be great to see them fixed at this wonderful adapter! :-)

**Comment by th4git** [comment]
Any updates on this?
Further feedback/support needed?

**Comment by Apollon77** [comment]
Please provide a debug log from the GitHub 2.0.1 version

**Comment by Apollon77** [comment]
Plesse try Github version if still happens

**Comment by thebilberry** [comment]
Sorry, but updating with Github-Version doesn't sovle the problem.

The following messages are still appearing
State value to set for "synology.0.DiskStationManager.vol_info.volume_1.used" has to be type "number" but received type "string"
State value to set for "synology.0.DiskStationManager.vol_info.volume_1.used_size" has to be type "number" but received type "string"
State value to set for "synology.0.DiskStationManager.vol_info.volume_1.total_size" has to be type "number" but received type "string" 

Additional after this update now six new messages can be found cyclic in Log:
State value to set for "synology.0.FileStation.info.items.1" has to be stringified but received type "object"
State value to set for "synology.0.FileStation.info.items.0" has to be stringified but received type "object"
State value to set for "synology.0.FileStation.info.enable_view_microsoft" has to be type "string" but received type "boolean"
State value to set for "synology.0.FileStation.info.enable_view_google" has to be type "string" but received type "boolean"
State value to set for "synology.0.FileStation.info.enable_send_email_attachment" has to be type "string" but received type "boolean"

**Comment by Apollon77** [comment]
Please provide a debug log of start of adater including these - nand make sure the install from github was really done!

**Comment by thebilberry** [comment]
You are right. I have to apologize. Apparently, the update went wrong and I didn't even notice it.
Now I have uninstalled the old version completly an reinstalled the latest Github-Version. The Message from "DiskStationManager" has disappeared, but not these from "FileStaion".

Here the comlete log after restart of the adapter:

```
2022-03-25 14:03:00.880 - debug: synology.0 (20202) Redis Objects: Use Redis connection: 0.0.0.0:9001
2022-03-25 14:03:00.942 - debug: synology.0 (20202) Objects client ready ... initialize now
2022-03-25 14:03:00.951 - debug: synology.0 (20202) Objects create System PubSub Client
2022-03-25 14:03:00.952 - debug: synology.0 (20202) Objects create User PubSub Client
2022-03-25 14:03:00.953 - debug: synology.0 (20202) Objects client initialize lua scripts
2022-03-25 14:03:01.025 - debug: synology.0 (20202) Objects connected to redis: 0.0.0.0:9001
2022-03-25 14:03:01.061 - debug: synology.0 (20202) objectDB connected
2022-03-25 14:03:01.063 - debug: synology.0 (20202) Redis States: Use Redis connection: 0.0.0.0:9000
2022-03-25 14:03:01.157 - debug: synology.0 (20202) States create System PubSub Client
2022-03-25 14:03:01.163 - debug: synology.0 (20202) States create User PubSub Client
2022-03-25 14:03:01.242 - debug: synology.0 (20202) States connected to redis: 0.0.0.0:9000
2022-03-25 14:03:01.244 - debug: synology.0 (20202) statesDB connected
2022-03-25 14:03:02.270 - debug: synology.0 (20202) Plugin sentry Initialize Plugin (enabled=true)
2022-03-25 14:03:02.851 - info: synology.0 (20202) starting. Version 2.1.0 in /opt/iobroker/node_modules/iobroker.synology, node: v12.22.6, js-controller: 3.3.22
2022-03-25 14:03:02.905 - info: synology.0 (20202) Connecting to Synology xxx.xxx.xxx.xxxx:5001
2022-03-25 14:03:05.873 - debug: synology.0 (20202) -----------------------------------------------------------------------------------------------------
2022-03-25 14:03:05.874 - debug: synology.0 (20202) * sendPolling. namePolling = firstPoll | iteration = 0 | typeof poll = object | poll = {"api":"dsm","method":"getPollingData","params":{}}
2022-03-25 14:03:05.879 - debug: synology.0 (20202) * Get info from (firstPoll) api: DSM method: getPollingData params: {}
2022-03-25 14:03:07.052 - debug: synology.0 (20202) * The response is received, parse:
2022-03-25 14:03:07.054 - debug: synology.0 (20202) InstallingPackets - Response: {"diskList":[]}
2022-03-25 14:03:07.055 - debug: synology.0 (20202) -----------------------------------------------------------------------------------------------------
2022-03-25 14:03:07.056 - debug: synology.0 (20202) * sendPolling. namePolling = firstPoll | iteration = 1 | typeof poll = object | poll = {"api":"dsm","method":"getInfo","params":{}}
2022-03-25 14:03:07.056 - debug: synology.0 (20202) * Get info from (firstPoll) api: DSM method: getInfo params: {}
2022-03-25 14:03:07.147 - debug: synology.0 (20202) * The response is received, parse:
2022-03-25 14:03:07.148 - debug: synology.0 (20202) Info - Response: {"codepage":"ger","model":"DSxxxx","ram":xxxxxx,"serial":"xxxxxxxxxxxxx","temperature":40,"temperature_warn":false,"time":"Fri Mar 25 14:03:07 2022","uptime":5349409,"version":"42218","version_string":"DSM 7.0.1-42218 Update 2"}
2022-03-25 14:03:07.149 - info: synology.0 (20202) DSM 2
2022-03-25 14:03:07.150 - debug: synology.0 (20202) -----------------------------------------------------------------------------------------------------
2022-03-25 14:03:07.150 - debug: synology.0 (20202) * sendPolling. namePolling = firstPoll | iteration = 2 | typeof poll = object | poll = {"api":"fs","method":"getInfo","params":{}}
2022-03-25 14:03:07.151 - debug: synology.0 (20202) * Get info from (firstPoll) api: FS method: getInfo params: {}
2022-03-25 14:03:07.864 - debug: synology.0 (20202) * The response is received, parse:
2022-03-25 14:03:07.865 - debug: synology.0 (20202) Info - Response: {"enable_list_usergrp":false,"enable_send_email_attachment":true,"enable_view_google":true,"enable_view_microsoft":true,"hostname":"xxx","is_manager":true,"items":[{"gid":100},{"gid":101}],"support_file_request":true,"support_sharing":true,"support_vfs":true,"support_virtual":{"enable_iso_mount":true,"enable_remote_mount":true},"support_virtual_protocol":["cifs","nfs","iso"],"system_codepage":"ger","uid":1028}
2022-03-25 14:03:07.866 - debug: synology.0 (20202) -----------------------------------------------------------------------------------------------------
2022-03-25 14:03:07.867 - debug: synology.0 (20202) * sendPolling. namePolling = firstPoll | iteration = 3 | typeof poll = object | poll = {"api":"dl","method":"getInfo","params":{}}
2022-03-25 14:03:07.867 - debug: synology.0 (20202) * Packet DL non installed, skipped
2022-03-25 14:03:07.868 - debug: synology.0 (20202) -----------------------------------------------------------------------------------------------------
2022-03-25 14:03:07.869 - debug: synology.0 (20202) * sendPolling. namePolling = firstPoll | iteration = 4 | typeof poll = object | poll = {"api":"as","method":"getInfo","params":{}}
2022-03-25 14:03:07.869 - debug: synology.0 (20202) * Packet AS non installed, skipped
2022-03-25 14:03:07.870 - debug: synology.0 (20202) -----------------------------------------------------------------------------------------------------
2022-03-25 14:03:07.870 - debug: synology.0 (20202) * sendPolling. namePolling = firstPoll | iteration = 5 | typeof poll = object | poll = {"api":"vs","method":"getInfo","params":{}}
2022-03-25 14:03:07.870 - debug: synology.0 (20202) * Packet VS non installed, skipped
2022-03-25 14:03:07.871 - debug: synology.0 (20202) -----------------------------------------------------------------------------------------------------
2022-03-25 14:03:07.871 - debug: synology.0 (20202) * sendPolling. namePolling = firstPoll | iteration = 6 | typeof poll = object | poll = {"api":"dtv","method":"GetInfoTuner","params":{}}
2022-03-25 14:03:07.872 - debug: synology.0 (20202) * Packet DTV non installed, skipped
2022-03-25 14:03:07.872 - debug: synology.0 (20202) -----------------------------------------------------------------------------------------------------
2022-03-25 14:03:07.873 - debug: synology.0 (20202) * sendPolling. namePolling = firstPoll | iteration = 7 | typeof poll = object | poll = {"api":"ss","method":"getInfo","params":{}}
2022-03-25 14:03:07.873 - debug: synology.0 (20202) * Packet SS non installed, skipped
2022-03-25 14:03:07.873 - debug: synology.0 (20202) -----------------------------------------------------------------------------------------------------
2022-03-25 14:03:07.874 - debug: synology.0 (20202) * sendPolling. namePolling = firstPoll | iteration = 8 | typeof poll = object | poll = {"api":"ss","method":"getInfoHomeMode","params":{"need_mobiles":true}}
2022-03-25 14:03:07.874 - debug: synology.0 (20202) * Packet SS non installed, skipped
2022-03-25 14:03:07.874 - debug: synology.0 (20202) -----------------------------------------------------------------------------------------------------
2022-03-25 14:03:07.875 - debug: synology.0 (20202) * sendPolling. namePolling = firstPoll | iteration = 9 | typeof poll = object | poll = {"api":"ss","method":"listCameras","params":{"basic":true,"version":7}}
2022-03-25 14:03:07.875 - debug: synology.0 (20202) * Packet SS non installed, skipped
2022-03-25 14:03:07.875 - debug: synology.0 (20202) -----------------------------------------------------------------------------------------------------
2022-03-25 14:03:07.875 - debug: synology.0 (20202) * sendPolling. namePolling = firstPoll | iteration = 10 | typeof poll = object | poll = {"api":"as","method":"listRemotePlayers","params":{"type":"all","additional":"subplayer_list"}}
2022-03-25 14:03:07.876 - debug: synology.0 (20202) * Packet AS non installed, skipped
2022-03-25 14:03:07.876 - debug: synology.0 (20202) -----------------------------------------------------------------------------------------------------
2022-03-25 14:03:07.877 - debug: synology.0 (20202) >>>>>>>>>>>>>>> Read all data, save received data.
2022-03-25 14:03:07.878 - debug: synology.0 (20202) setStates
2022-03-25 14:03:07.879 - debug: synology.0 (20202) setObject "DiskStationManager.info.codepage", val=ger
2022-03-25 14:03:07.978 - debug: synology.0 (20202) setObject "DiskStationManager.info.model", val=DSxxxx
2022-03-25 14:03:07.980 - debug: synology.0 (20202) -----------------------------------------------------------------------------------------------------
2022-03-25 14:03:07.980 - debug: synology.0 (20202) * sendPolling. namePolling = fastPoll | iteration = 0 | typeof poll = object | poll = {"api":"dsm","method":"getSystemUtilization","params":{}}
2022-03-25 14:03:07.981 - debug: synology.0 (20202) * Get info from (fastPoll) api: DSM method: getSystemUtilization params: {}
2022-03-25 14:03:08.054 - debug: synology.0 (20202) setObject "DiskStationManager.info.ram", val=xxxxxx
2022-03-25 14:03:08.067 - debug: synology.0 (20202) setObject "DiskStationManager.info.serial", val=xxxxxxxxxxxxx
2022-03-25 14:03:08.080 - debug: synology.0 (20202) setObject "DiskStationManager.info.temperature", val=40
2022-03-25 14:03:08.099 - debug: synology.0 (20202) setObject "DiskStationManager.info.temperature_warn", val=false
2022-03-25 14:03:08.114 - debug: synology.0 (20202) setObject "DiskStationManager.info.time", val=Fri Mar 25 14:03:07 2022
2022-03-25 14:03:08.132 - debug: synology.0 (20202) setObject "DiskStationManager.info.uptime", val=5349409
2022-03-25 14:03:08.146 - debug: synology.0 (20202) setObject "DiskStationManager.info.version", val=42218
2022-03-25 14:03:08.158 - debug: synology.0 (20202) setObject "DiskStationManager.info.version_string", val=DSM 7.0.1-42218 Update 2
2022-03-25 14:03:08.173 - debug: synology.0 (20202) setObject "FileStation.info.enable_list_usergrp", val=false
2022-03-25 14:03:08.187 - debug: synology.0 (20202) setObject "FileStation.info.enable_send_email_attachment", val=true
2022-03-25 14:03:08.197 - info: synology.0 (20202) State value to set for "synology.0.FileStation.info.enable_send_email_attachment" has to be type "string" but received type "boolean"
2022-03-25 14:03:08.249 - debug: synology.0 (20202) setObject "FileStation.info.enable_view_google", val=true
2022-03-25 14:03:08.256 - info: synology.0 (20202) State value to set for "synology.0.FileStation.info.enable_view_google" has to be type "string" but received type "boolean"
2022-03-25 14:03:08.311 - debug: synology.0 (20202) setObject "FileStation.info.enable_view_microsoft", val=true
2022-03-25 14:03:08.317 - info: synology.0 (20202) State value to set for "synology.0.FileStation.info.enable_view_microsoft" has to be type "string" but received type "boolean"
2022-03-25 14:03:08.366 - debug: synology.0 (20202) setObject "FileStation.info.hostname", val=xxx
2022-03-25 14:03:08.382 - debug: synology.0 (20202) setObject "FileStation.info.is_manager", val=true
2022-03-25 14:03:08.396 - debug: synology.0 (20202) setObject "FileStation.info.items.0", val=[object Object]
2022-03-25 14:03:08.403 - info: synology.0 (20202) State value to set for "synology.0.FileStation.info.items.0" has to be stringified but received type "object"
2022-03-25 14:03:08.456 - debug: synology.0 (20202) setObject "FileStation.info.items.1", val=[object Object]
2022-03-25 14:03:08.462 - info: synology.0 (20202) State value to set for "synology.0.FileStation.info.items.1" has to be stringified but received type "object"
2022-03-25 14:03:08.516 - debug: synology.0 (20202) setObject "FileStation.info.support_file_request", val=true
2022-03-25 14:03:08.528 - debug: synology.0 (20202) setObject "FileStation.info.support_sharing", val=true
2022-03-25 14:03:08.541 - debug: synology.0 (20202) setObject "FileStation.info.support_vfs", val=true
2022-03-25 14:03:08.554 - debug: synology.0 (20202) setObject "FileStation.info.support_virtual.enable_iso_mount", val=true
2022-03-25 14:03:08.574 - debug: synology.0 (20202) setObject "FileStation.info.support_virtual.enable_remote_mount", val=true
2022-03-25 14:03:08.589 - debug: synology.0 (20202) setObject "FileStation.info.support_virtual_protocol.0", val=cifs
2022-03-25 14:03:08.604 - debug: synology.0 (20202) setObject "FileStation.info.support_virtual_protocol.1", val=nfs
2022-03-25 14:03:08.652 - debug: synology.0 (20202) setObject "FileStation.info.support_virtual_protocol.2", val=iso
2022-03-25 14:03:08.665 - debug: synology.0 (20202) setObject "FileStation.info.system_codepage", val=ger
2022-03-25 14:03:08.682 - debug: synology.0 (20202) setObject "FileStation.info.uid", val=1028
2022-03-25 14:03:09.074 - debug: synology.0 (20202) * The response is received, parse:
2022-03-25 14:03:09.075 - debug: synology.0 (20202) SystemUtilization - Response: {...}
```

**Comment by Apollon77** [comment]
Hey, yes the FileStation errors where not reported before .-)) Please try GitHb version again ... should be fixed now. (version number stays same)
